version: '3.8'

services:
  # PostgreSQL 15 - Main database
  postgres:
    image: postgres:15-alpine
    container_name: dentalai-postgres
    environment:
      POSTGRES_DB: dentalai
      POSTGRES_USER: dentalai
      POSTGRES_PASSWORD: dentalai_dev_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=en_US.UTF-8 --lc-ctype=en_US.UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dentalai"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dentalai-network

  # Redis 7.0 - Cache and session store
  redis:
    image: redis:7.0-alpine
    container_name: dentalai-redis
    command: redis-server --appendonly yes --requirepass dentalai_redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dentalai-network

  # Neo4j - Causal Memory Graph Database
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  neo4j_data:
    driver: local
  neo4j_logs:
    driver: local
  odoo_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  dentalai-network:
    driver: bridge
