version: '3.8'

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: dental-clinic-mysql
    environment:
      MYSQL_ROOT_PASSWORD: dental_clinic_secure_2025
      MYSQL_DATABASE: dental_clinic_demo
      MYSQL_USER: dental_user
      MYSQL_PASSWORD: dental_pass_2025
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    networks:
      - dental_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis Service for Message Queue
  redis:
    image: redis:7-alpine
    container_name: dental-clinic-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dental_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Gateway Service (FastAPI)
  gateway:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.gateway
    container_name: dental-clinic-gateway
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MYSQL_HOST=mysql
      - MYSQL_USER=dental_user
      - MYSQL_PASSWORD=dental_pass_2025
      - MYSQL_DATABASE=dental_clinic_demo
      - REDIS_URL=redis://redis:6379/0
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - LOG_LEVEL=INFO
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dental_network
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # AI Agents Service
  ai-agents:
    build:
      context: .
      dockerfile: infrastructure/docker/Dockerfile.agents
    container_name: dental-clinic-ai-agents
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MYSQL_HOST=mysql
      - MYSQL_USER=dental_user
      - MYSQL_PASSWORD=dental_pass_2025
      - MYSQL_DATABASE=dental_clinic_demo
      - REDIS_URL=redis://redis:6379/0
      - APP_HOST=0.0.0.0
      - APP_PORT=8001
      - LOG_LEVEL=INFO
    ports:
      - "8001:8001"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - dental_network
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
  redis_data:

networks:
  dental_network:
    driver: bridge
