"""
Compliance Alert Model

Stores HIPAA compliance alerts generated by Harper's proactive monitoring system.
"""

from sqlalchemy import Column, Integer, String, DateTime, Text, JSON, Index, Boolean, ForeignKey, Enum as SQLEnum
from datetime import datetime
from enum import Enum

from app.core.database import Base


class AlertSeverity(str, Enum):
    """Alert severity levels."""
    CRITICAL = "critical"  # Immediate action required
    HIGH = "high"  # Action required within 24 hours
    MEDIUM = "medium"  # Action required within 1 week
    LOW = "low"  # Informational, no immediate action
    INFO = "info"  # General information


class AlertType(str, Enum):
    """Types of compliance alerts."""
    BAA_EXPIRING = "baa_expiring"
    BAA_EXPIRED = "baa_expired"
    PHI_COMPLIANCE_ISSUE = "phi_compliance_issue"
    SECURITY_GAP = "security_gap"
    ACCESS_ANOMALY = "access_anomaly"
    RISK_THRESHOLD_EXCEEDED = "risk_threshold_exceeded"
    BREACH_DETECTED = "breach_detected"
    PATIENT_RIGHTS_VIOLATION = "patient_rights_violation"
    AUDIT_FINDING = "audit_finding"
    COMPLIANCE_SCORE_DROP = "compliance_score_drop"


class AlertStatus(str, Enum):
    """Alert status."""
    OPEN = "open"  # New alert, not yet acknowledged
    ACKNOWLEDGED = "acknowledged"  # Acknowledged by admin
    IN_PROGRESS = "in_progress"  # Being worked on
    RESOLVED = "resolved"  # Issue resolved
    DISMISSED = "dismissed"  # Alert dismissed (false positive or not applicable)


class ComplianceAlert(Base):
    """
    HIPAA compliance alerts generated by Harper's proactive monitoring.
    
    These alerts notify clinic administrators of compliance issues that
    require attention, such as expiring BAAs, security gaps, or PHI
    access anomalies.
    """
    __tablename__ = "compliance_alerts"
    
    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Organization
    organization_id = Column(Integer, ForeignKey("organizations.id"), nullable=False, index=True)
    
    # Alert metadata
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Alert classification
    alert_type = Column(SQLEnum(AlertType), nullable=False, index=True)
    severity = Column(SQLEnum(AlertSeverity), nullable=False, index=True)
    status = Column(SQLEnum(AlertStatus), default=AlertStatus.OPEN, nullable=False, index=True)
    
    # Alert content
    title = Column(String(500), nullable=False)
    description = Column(Text)
    action_required = Column(Text)  # What needs to be done
    
    # Deadline
    deadline = Column(String(100))  # "IMMEDIATE", "2024-12-31", "Within 24 hours", etc.
    deadline_date = Column(DateTime)  # Parsed deadline for sorting/filtering
    
    # Additional data
    metadata = Column(JSON)  # Additional context (e.g., BAA details, risk scores)
    
    # Resolution tracking
    acknowledged_at = Column(DateTime)
    acknowledged_by = Column(Integer, ForeignKey("users.id"))  # User who acknowledged
    
    resolved_at = Column(DateTime)
    resolved_by = Column(Integer, ForeignKey("users.id"))  # User who resolved
    resolution_notes = Column(Text)
    
    dismissed_at = Column(DateTime)
    dismissed_by = Column(Integer, ForeignKey("users.id"))  # User who dismissed
    dismissal_reason = Column(Text)
    
    # Related entities
    related_entity_type = Column(String(50))  # "baa", "user", "patient", etc.
    related_entity_id = Column(Integer)
    
    # Notification tracking
    notification_sent = Column(Boolean, default=False)
    notification_sent_at = Column(DateTime)
    notification_channels = Column(JSON)  # ["email", "sms", "dashboard"]
    
    # Recurrence tracking (for recurring checks)
    is_recurring = Column(Boolean, default=False)
    recurrence_key = Column(String(255), index=True)  # Unique key for recurring alerts
    last_occurrence_id = Column(Integer)  # ID of previous occurrence
    
    # Indexes for common queries
    __table_args__ = (
        Index('idx_org_status', 'organization_id', 'status'),
        Index('idx_org_severity', 'organization_id', 'severity'),
        Index('idx_org_type', 'organization_id', 'alert_type'),
        Index('idx_org_created', 'organization_id', 'created_at'),
        Index('idx_deadline', 'deadline_date'),
        Index('idx_recurrence', 'recurrence_key', 'created_at'),
    )
    
    def __repr__(self):
        return f"<ComplianceAlert {self.id}: {self.alert_type} - {self.severity} - {self.status}>"
    
    @classmethod
    def create_alert(
        cls,
        organization_id: int,
        alert_type: AlertType,
        severity: AlertSeverity,
        title: str,
        description: str = None,
        action_required: str = None,
        deadline: str = None,
        deadline_date: datetime = None,
        metadata: dict = None,
        related_entity_type: str = None,
        related_entity_id: int = None,
        is_recurring: bool = False,
        recurrence_key: str = None
    ):
        """
        Create a new compliance alert.
        
        Args:
            organization_id: Organization ID
            alert_type: Type of alert
            severity: Alert severity
            title: Alert title
            description: Detailed description
            action_required: What needs to be done
            deadline: Deadline string
            deadline_date: Parsed deadline datetime
            metadata: Additional context
            related_entity_type: Type of related entity
            related_entity_id: ID of related entity
            is_recurring: Whether this is a recurring alert
            recurrence_key: Unique key for recurring alerts
            
        Returns:
            New ComplianceAlert instance
        """
        return cls(
            organization_id=organization_id,
            alert_type=alert_type,
            severity=severity,
            title=title,
            description=description,
            action_required=action_required,
            deadline=deadline,
            deadline_date=deadline_date,
            metadata=metadata,
            related_entity_type=related_entity_type,
            related_entity_id=related_entity_id,
            is_recurring=is_recurring,
            recurrence_key=recurrence_key
        )
    
    def acknowledge(self, user_id: int):
        """Mark alert as acknowledged."""
        self.status = AlertStatus.ACKNOWLEDGED
        self.acknowledged_at = datetime.utcnow()
        self.acknowledged_by = user_id
        self.updated_at = datetime.utcnow()
    
    def start_progress(self):
        """Mark alert as in progress."""
        self.status = AlertStatus.IN_PROGRESS
        self.updated_at = datetime.utcnow()
    
    def resolve(self, user_id: int, notes: str = None):
        """Mark alert as resolved."""
        self.status = AlertStatus.RESOLVED
        self.resolved_at = datetime.utcnow()
        self.resolved_by = user_id
        self.resolution_notes = notes
        self.updated_at = datetime.utcnow()
    
    def dismiss(self, user_id: int, reason: str = None):
        """Dismiss alert."""
        self.status = AlertStatus.DISMISSED
        self.dismissed_at = datetime.utcnow()
        self.dismissed_by = user_id
        self.dismissal_reason = reason
        self.updated_at = datetime.utcnow()
    
    def to_dict(self) -> dict:
        """Convert alert to dictionary."""
        return {
            "id": self.id,
            "organization_id": self.organization_id,
            "alert_type": self.alert_type.value if self.alert_type else None,
            "severity": self.severity.value if self.severity else None,
            "status": self.status.value if self.status else None,
            "title": self.title,
            "description": self.description,
            "action_required": self.action_required,
            "deadline": self.deadline,
            "deadline_date": self.deadline_date.isoformat() if self.deadline_date else None,
            "metadata": self.metadata,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
            "acknowledged_at": self.acknowledged_at.isoformat() if self.acknowledged_at else None,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "related_entity_type": self.related_entity_type,
            "related_entity_id": self.related_entity_id,
        }


class ComplianceMetric(Base):
    """
    Compliance metrics tracked over time.
    
    Used for trend analysis and dashboard visualization.
    """
    __tablename__ = "compliance_metrics"
    
    # Primary key
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Organization
    organization_id = Column(Integer, ForeignKey("organizations.id"), nullable=False, index=True)
    
    # Timestamp
    recorded_at = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
    
    # Metric type
    metric_type = Column(String(50), nullable=False, index=True)  # "compliance_score", "phi_score", etc.
    
    # Metric value
    value = Column(Integer)  # Score (0-100)
    details = Column(JSON)  # Detailed breakdown
    
    # Period
    period_type = Column(String(20))  # "daily", "weekly", "monthly"
    period_start = Column(DateTime)
    period_end = Column(DateTime)
    
    # Indexes
    __table_args__ = (
        Index('idx_org_metric_time', 'organization_id', 'metric_type', 'recorded_at'),
        Index('idx_period', 'period_type', 'period_start'),
    )
    
    def __repr__(self):
        return f"<ComplianceMetric {self.id}: {self.metric_type} = {self.value}>"

