steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/dentaflow-production/cloud-run-source-deploy/dentaflow-backend:$SHORT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/dentaflow-production/cloud-run-source-deploy/dentaflow-backend:$SHORT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dentaflow-backend'
      - '--image'
      - 'us-central1-docker.pkg.dev/dentaflow-production/cloud-run-source-deploy/dentaflow-backend:$SHORT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'

images:
  - 'us-central1-docker.pkg.dev/dentaflow-production/cloud-run-source-deploy/dentaflow-backend:$SHORT_SHA'
