# Prometheus Configuration for AI Dental Clinic System
# הגדרות ניטור למערכת ניהול מרפאת שיניים AI

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'dental-clinic-ai'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Gateway Service
  - job_name: 'gateway'
    static_configs:
      - targets: ['gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # AI Agents Service
  - job_name: 'ai-agents'
    static_configs:
      - targets: ['ai-agents:8001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s

  # MySQL Exporter
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
    scrape_interval: 10s

  # Node Exporter (System metrics)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # cAdvisor (Container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s

  # Custom application metrics
  - job_name: 'dental-clinic-metrics'
    static_configs:
      - targets: ['gateway:8000', 'ai-agents:8001']
    metrics_path: '/api/metrics'
    scrape_interval: 30s
    params:
      format: ['prometheus']

# Remote write configuration (for long-term storage)
remote_write:
  - url: "https://prometheus-remote-write-endpoint/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
