/**
 * Compliance Alerts Component
 * 
 * Displays and manages HIPAA compliance alerts generated by Harper's
 * proactive monitoring system.
 */

import React, { useState } from 'react';
import { 
  AlertTriangle, 
  CheckCircle, 
  Clock, 
  X, 
  Eye,
  Play,
  Check,
  XCircle
} from 'lucide-react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../ui/card';
import { Button } from '../ui/button';
import { Badge } from '../ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '../ui/dialog';
import { Textarea } from '../ui/textarea';
import { Label } from '../ui/label';

const ComplianceAlerts = ({ alerts, onRefresh }) => {
  const [selectedAlert, setSelectedAlert] = useState(null);
  const [actionDialog, setActionDialog] = useState({ open: false, action: null });
  const [notes, setNotes] = useState('');
  const [loading, setLoading] = useState(false);

  const getSeverityColor = (severity) => {
    const colors = {
      critical: 'destructive',
      high: 'destructive',
      medium: 'warning',
      low: 'secondary',
      info: 'default'
    };
    return colors[severity] || 'default';
  };

  const getSeverityIcon = (severity) => {
    if (severity === 'critical' || severity === 'high') {
      return <AlertTriangle className="w-4 h-4" />;
    }
    if (severity === 'medium') {
      return <Clock className="w-4 h-4" />;
    }
    return <CheckCircle className="w-4 h-4" />;
  };

  const getStatusBadge = (status) => {
    const variants = {
      open: 'destructive',
      acknowledged: 'warning',
      in_progress: 'default',
      resolved: 'success',
      dismissed: 'secondary'
    };
    return variants[status] || 'default';
  };

  const handleAlertAction = async (alert, action) => {
    setSelectedAlert(alert);
    setActionDialog({ open: true, action });
  };

  const confirmAction = async () => {
    setLoading(true);
    try {
      const endpoint = `/api/compliance/alerts/${selectedAlert.id}/${actionDialog.action}`;
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          notes: notes || undefined
        })
      });

      if (!response.ok) {
        throw new Error('Failed to update alert');
      }

      // Refresh alerts
      onRefresh();
      
      // Close dialog
      setActionDialog({ open: false, action: null });
      setSelectedAlert(null);
      setNotes('');

    } catch (error) {
      console.error('Error updating alert:', error);
      alert('Failed to update alert. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const filterAlertsByStatus = (status) => {
    if (status === 'all') return alerts;
    return alerts.filter(a => a.status === status);
  };

  const openAlerts = filterAlertsByStatus('open');
  const acknowledgedAlerts = filterAlertsByStatus('acknowledged');
  const inProgressAlerts = filterAlertsByStatus('in_progress');
  const resolvedAlerts = filterAlertsByStatus('resolved');

  const AlertCard = ({ alert }) => (
    <Card className="mb-4">
      <CardHeader>
        <div className="flex items-start justify-between">
          <div className="flex-1">
            <div className="flex items-center gap-2 mb-2">
              <Badge variant={getSeverityColor(alert.severity)} className="flex items-center gap-1">
                {getSeverityIcon(alert.severity)}
                {alert.severity.toUpperCase()}
              </Badge>
              <Badge variant={getStatusBadge(alert.status)}>
                {alert.status.replace('_', ' ').toUpperCase()}
              </Badge>
              {alert.deadline && (
                <Badge variant="outline" className="flex items-center gap-1">
                  <Clock className="w-3 h-3" />
                  {alert.deadline}
                </Badge>
              )}
            </div>
            <CardTitle className="text-lg">{alert.title}</CardTitle>
            <CardDescription className="mt-2">
              {alert.description}
            </CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {alert.action_required && (
          <div className="bg-blue-50 border border-blue-200 rounded-lg p-3 mb-4">
            <p className="text-sm font-medium text-blue-900 mb-1">Action Required:</p>
            <p className="text-sm text-blue-800">{alert.action_required}</p>
          </div>
        )}

        <div className="flex gap-2 flex-wrap">
          {alert.status === 'open' && (
            <>
              <Button
                size="sm"
                variant="outline"
                onClick={() => handleAlertAction(alert, 'acknowledge')}
              >
                <Eye className="w-4 h-4 mr-1" />
                Acknowledge
              </Button>
              <Button
                size="sm"
                variant="outline"
                onClick={() => handleAlertAction(alert, 'start_progress')}
              >
                <Play className="w-4 h-4 mr-1" />
                Start Working
              </Button>
            </>
          )}

          {(alert.status === 'acknowledged' || alert.status === 'in_progress') && (
            <>
              <Button
                size="sm"
                variant="default"
                onClick={() => handleAlertAction(alert, 'resolve')}
              >
                <Check className="w-4 h-4 mr-1" />
                Mark Resolved
              </Button>
              {alert.status === 'acknowledged' && (
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => handleAlertAction(alert, 'start_progress')}
                >
                  <Play className="w-4 h-4 mr-1" />
                  Start Working
                </Button>
              )}
            </>
          )}

          {alert.status !== 'dismissed' && alert.status !== 'resolved' && (
            <Button
              size="sm"
              variant="ghost"
              onClick={() => handleAlertAction(alert, 'dismiss')}
            >
              <XCircle className="w-4 h-4 mr-1" />
              Dismiss
            </Button>
          )}
        </div>

        {alert.metadata && (
          <div className="mt-4 pt-4 border-t">
            <p className="text-xs text-gray-500 mb-2">Additional Information:</p>
            <pre className="text-xs bg-gray-50 p-2 rounded overflow-x-auto">
              {JSON.stringify(alert.metadata, null, 2)}
            </pre>
          </div>
        )}
      </CardContent>
    </Card>
  );

  return (
    <>
      <Card>
        <CardHeader>
          <CardTitle>Compliance Alerts</CardTitle>
          <CardDescription>
            Monitor and manage HIPAA compliance issues
          </CardDescription>
        </CardHeader>
        <CardContent>
          <Tabs defaultValue="open" className="w-full">
            <TabsList className="grid w-full grid-cols-5">
              <TabsTrigger value="open">
                Open ({openAlerts.length})
              </TabsTrigger>
              <TabsTrigger value="acknowledged">
                Acknowledged ({acknowledgedAlerts.length})
              </TabsTrigger>
              <TabsTrigger value="in_progress">
                In Progress ({inProgressAlerts.length})
              </TabsTrigger>
              <TabsTrigger value="resolved">
                Resolved ({resolvedAlerts.length})
              </TabsTrigger>
              <TabsTrigger value="all">
                All ({alerts.length})
              </TabsTrigger>
            </TabsList>

            <TabsContent value="open" className="mt-4">
              {openAlerts.length === 0 ? (
                <div className="text-center py-8 text-gray-500">
                  <CheckCircle className="w-12 h-12 mx-auto mb-2 text-green-500" />
                  <p>No open alerts. Great job!</p>
                </div>
              ) : (
                openAlerts.map(alert => <AlertCard key={alert.id} alert={alert} />)
              )}
            </TabsContent>

            <TabsContent value="acknowledged" className="mt-4">
              {acknowledgedAlerts.length === 0 ? (
                <div className="text-center py-8 text-gray-500">
                  <p>No acknowledged alerts</p>
                </div>
              ) : (
                acknowledgedAlerts.map(alert => <AlertCard key={alert.id} alert={alert} />)
              )}
            </TabsContent>

            <TabsContent value="in_progress" className="mt-4">
              {inProgressAlerts.length === 0 ? (
                <div className="text-center py-8 text-gray-500">
                  <p>No alerts in progress</p>
                </div>
              ) : (
                inProgressAlerts.map(alert => <AlertCard key={alert.id} alert={alert} />)
              )}
            </TabsContent>

            <TabsContent value="resolved" className="mt-4">
              {resolvedAlerts.length === 0 ? (
                <div className="text-center py-8 text-gray-500">
                  <p>No resolved alerts</p>
                </div>
              ) : (
                resolvedAlerts.map(alert => <AlertCard key={alert.id} alert={alert} />)
              )}
            </TabsContent>

            <TabsContent value="all" className="mt-4">
              {alerts.map(alert => <AlertCard key={alert.id} alert={alert} />)}
            </TabsContent>
          </Tabs>
        </CardContent>
      </Card>

      {/* Action Confirmation Dialog */}
      <Dialog open={actionDialog.open} onOpenChange={(open) => setActionDialog({ open, action: null })}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>
              {actionDialog.action === 'acknowledge' && 'Acknowledge Alert'}
              {actionDialog.action === 'start_progress' && 'Start Working on Alert'}
              {actionDialog.action === 'resolve' && 'Mark Alert as Resolved'}
              {actionDialog.action === 'dismiss' && 'Dismiss Alert'}
            </DialogTitle>
            <DialogDescription>
              {selectedAlert && selectedAlert.title}
            </DialogDescription>
          </DialogHeader>

          <div className="space-y-4">
            <div>
              <Label htmlFor="notes">
                {actionDialog.action === 'resolve' ? 'Resolution Notes' : 'Notes (Optional)'}
              </Label>
              <Textarea
                id="notes"
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                placeholder={
                  actionDialog.action === 'resolve'
                    ? 'Describe how this issue was resolved...'
                    : actionDialog.action === 'dismiss'
                    ? 'Reason for dismissing this alert...'
                    : 'Add any relevant notes...'
                }
                rows={4}
                className="mt-1"
              />
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setActionDialog({ open: false, action: null })}>
              Cancel
            </Button>
            <Button onClick={confirmAction} disabled={loading}>
              {loading ? 'Processing...' : 'Confirm'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
};

export default ComplianceAlerts;

