"""Initial migration from scratch

Revision ID: 8331bae54d16
Revises: 
Create Date: 2025-10-10 08:04:55.420101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.database_types as dt


# revision identifiers, used by Alembic.
revision: str = '8331bae54d16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', dt.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('subscription_tier', sa.Enum('BASIC', 'PROFESSIONAL', 'ENTERPRISE', name='subscriptiontier'), nullable=False),
    sa.Column('subscription_status', sa.String(length=50), nullable=False),
    sa.Column('subscription_start_date', sa.DateTime(), nullable=True),
    sa.Column('subscription_end_date', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('odoo_db_name', sa.String(length=255), nullable=True),
    sa.Column('odoo_api_key', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('odoo_db_name'),
    sa.UniqueConstraint('stripe_customer_id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('clinic_settings',
    sa.Column('id', dt.UUID(), nullable=False),
    sa.Column('organization_id', dt.UUID(), nullable=False),
    sa.Column('sunday_open', sa.Time(), nullable=True),
    sa.Column('sunday_close', sa.Time(), nullable=True),
    sa.Column('monday_open', sa.Time(), nullable=True),
    sa.Column('monday_close', sa.Time(), nullable=True),
    sa.Column('tuesday_open', sa.Time(), nullable=True),
    sa.Column('tuesday_close', sa.Time(), nullable=True),
    sa.Column('wednesday_open', sa.Time(), nullable=True),
    sa.Column('wednesday_close', sa.Time(), nullable=True),
    sa.Column('thursday_open', sa.Time(), nullable=True),
    sa.Column('thursday_close', sa.Time(), nullable=True),
    sa.Column('friday_open', sa.Time(), nullable=True),
    sa.Column('friday_close', sa.Time(), nullable=True),
    sa.Column('saturday_open', sa.Time(), nullable=True),
    sa.Column('saturday_close', sa.Time(), nullable=True),
    sa.Column('default_appointment_duration', sa.Integer(), nullable=False, comment='Default appointment duration in minutes'),
    sa.Column('buffer_between_appointments', sa.Integer(), nullable=False, comment='Buffer time between appointments in minutes'),
    sa.Column('advance_booking_days', sa.Integer(), nullable=False, comment='How many days in advance patients can book'),
    sa.Column('cancellation_notice_hours', sa.Integer(), nullable=False, comment='Required notice for cancellation (hours)'),
    sa.Column('no_show_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='Fee for no-show appointments (ILS)'),
    sa.Column('allow_online_booking', sa.Boolean(), nullable=False, comment='Allow patients to book online'),
    sa.Column('require_deposit', sa.Boolean(), nullable=False, comment='Require deposit for appointments'),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=True, comment='Deposit amount if required (ILS)'),
    sa.Column('sms_enabled', sa.Boolean(), nullable=False, comment='Enable SMS notifications'),
    sa.Column('email_enabled', sa.Boolean(), nullable=False, comment='Enable email notifications'),
    sa.Column('whatsapp_enabled', sa.Boolean(), nullable=False, comment='Enable WhatsApp notifications'),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False, comment='Enable Telegram notifications'),
    sa.Column('reminder_hours_before', sa.Integer(), nullable=False, comment='Send appointment reminder X hours before'),
    sa.Column('send_followup_after_hours', sa.Integer(), nullable=False, comment='Send follow-up message X hours after appointment'),
    sa.Column('send_recall_after_months', sa.Integer(), nullable=False, comment='Send recall reminder after X months'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency code (ISO 4217)'),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='VAT/Tax rate percentage (Israel: 17%)'),
    sa.Column('payment_methods', sa.JSON(), nullable=False, comment='Accepted payment methods'),
    sa.Column('invoice_prefix', sa.String(length=10), nullable=True, comment="Invoice number prefix (e.g., 'INV-')"),
    sa.Column('invoice_starting_number', sa.Integer(), nullable=False, comment='Starting invoice number'),
    sa.Column('clinic_name_hebrew', sa.String(length=255), nullable=True, comment='Clinic name in Hebrew'),
    sa.Column('clinic_name_english', sa.String(length=255), nullable=True, comment='Clinic name in English'),
    sa.Column('clinic_logo_url', sa.String(length=500), nullable=True, comment='URL to clinic logo image'),
    sa.Column('clinic_address', sa.Text(), nullable=True, comment='Full clinic address'),
    sa.Column('clinic_phone', sa.String(length=20), nullable=True, comment='Clinic phone number'),
    sa.Column('clinic_email', sa.String(length=255), nullable=True, comment='Clinic email address'),
    sa.Column('clinic_website', sa.String(length=255), nullable=True, comment='Clinic website URL'),
    sa.Column('business_license_number', sa.String(length=50), nullable=True, comment='Israeli business license number'),
    sa.Column('tax_id', sa.String(length=50), nullable=True, comment="Israeli tax ID (מס' עוסק מורשה)"),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', name='uq_clinic_settings_org')
    )
    op.create_index(op.f('ix_clinic_settings_organization_id'), 'clinic_settings', ['organization_id'], unique=True)
    op.create_table('conversations',
    sa.Column('id', dt.UUID(), nullable=False),
    sa.Column('organization_id', dt.UUID(), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=True),
    sa.Column('patient_email', sa.String(length=255), nullable=True),
    sa.Column('patient_phone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'ESCALATED', 'FAILED', name='conversationstatus'), nullable=False),
    sa.Column('channel', sa.Enum('WEB_CHAT', 'WHATSAPP', 'TELEGRAM', 'SMS', name='conversationchannel'), nullable=False),
    sa.Column('primary_agent', sa.String(length=50), nullable=False),
    sa.Column('escalated_to_agent', sa.String(length=50), nullable=True),
    sa.Column('langgraph_thread_id', sa.String(length=255), nullable=False),
    sa.Column('langgraph_state', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_langgraph_thread_id'), 'conversations', ['langgraph_thread_id'], unique=True)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_table('treatment_prices',
    sa.Column('id', dt.UUID(), nullable=False),
    sa.Column('organization_id', dt.UUID(), nullable=False),
    sa.Column('treatment_code', sa.String(length=50), nullable=False, comment="Unique treatment code (e.g., 'CLEAN-001', 'FILL-002')"),
    sa.Column('treatment_name_hebrew', sa.String(length=255), nullable=False, comment='Treatment name in Hebrew'),
    sa.Column('treatment_name_english', sa.String(length=255), nullable=True, comment='Treatment name in English'),
    sa.Column('category', sa.String(length=100), nullable=False, comment="Treatment category (e.g., 'preventive', 'restorative', 'cosmetic')"),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed treatment description'),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='Base price for treatment (ILS)'),
    sa.Column('member_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Discounted price for members (ILS)'),
    sa.Column('insurance_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='Price covered by insurance (ILS)'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='Currency code (ISO 4217)'),
    sa.Column('duration_minutes', sa.Integer(), nullable=False, comment='Estimated treatment duration in minutes'),
    sa.Column('requires_specialist', sa.Boolean(), nullable=False, comment='Whether treatment requires a specialist'),
    sa.Column('specialist_type', sa.String(length=100), nullable=True, comment="Type of specialist required (e.g., 'orthodontist', 'endodontist')"),
    sa.Column('odoo_product_id', sa.Integer(), nullable=True, comment='Odoo product.product ID'),
    sa.Column('odoo_product_template_id', sa.Integer(), nullable=True, comment='Odoo product.template ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Whether treatment is currently offered'),
    sa.Column('is_visible_online', sa.Boolean(), nullable=False, comment='Whether treatment is visible in online booking'),
    sa.Column('requires_approval', sa.Boolean(), nullable=False, comment='Whether treatment requires manager approval'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Internal notes about treatment'),
    sa.Column('display_order', sa.Integer(), nullable=True, comment='Order for displaying in lists'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'treatment_code', name='uq_org_treatment_code')
    )
    op.create_index(op.f('ix_treatment_prices_category'), 'treatment_prices', ['category'], unique=False)
    op.create_index(op.f('ix_treatment_prices_is_active'), 'treatment_prices', ['is_active'], unique=False)
    op.create_index(op.f('ix_treatment_prices_odoo_product_id'), 'treatment_prices', ['odoo_product_id'], unique=False)
    op.create_index(op.f('ix_treatment_prices_organization_id'), 'treatment_prices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_treatment_prices_treatment_code'), 'treatment_prices', ['treatment_code'], unique=False)
    op.create_table('users',
    sa.Column('id', dt.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('picture_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ORG_ADMIN', 'ORG_STAFF', 'ORG_VIEWER', name='userrole'), nullable=False),
    sa.Column('organization_id', dt.UUID(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_table('messages',
    sa.Column('id', dt.UUID(), nullable=False),
    sa.Column('conversation_id', dt.UUID(), nullable=False),
    sa.Column('organization_id', dt.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('agent_name', sa.String(length=50), nullable=True),
    sa.Column('message_metadata', sa.JSON(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_organization_id'), 'messages', ['organization_id'], unique=False)
    op.create_table('organization_memberships',
    sa.Column('id', dt.UUID(), nullable=False),
    sa.Column('user_id', dt.UUID(), nullable=False),
    sa.Column('organization_id', dt.UUID(), nullable=False),
    sa.Column('organization_role', sa.String(length=50), nullable=False),
    sa.Column('functional_role', sa.String(length=50), nullable=True),
    sa.Column('odoo_partner_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_org')
    )
    op.create_index(op.f('ix_organization_memberships_odoo_partner_id'), 'organization_memberships', ['odoo_partner_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_organization_id'), 'organization_memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_organization_memberships_user_id'), 'organization_memberships', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_memberships_user_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_organization_id'), table_name='organization_memberships')
    op.drop_index(op.f('ix_organization_memberships_odoo_partner_id'), table_name='organization_memberships')
    op.drop_table('organization_memberships')
    op.drop_index(op.f('ix_messages_organization_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_treatment_prices_treatment_code'), table_name='treatment_prices')
    op.drop_index(op.f('ix_treatment_prices_organization_id'), table_name='treatment_prices')
    op.drop_index(op.f('ix_treatment_prices_odoo_product_id'), table_name='treatment_prices')
    op.drop_index(op.f('ix_treatment_prices_is_active'), table_name='treatment_prices')
    op.drop_index(op.f('ix_treatment_prices_category'), table_name='treatment_prices')
    op.drop_table('treatment_prices')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_langgraph_thread_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_clinic_settings_organization_id'), table_name='clinic_settings')
    op.drop_table('clinic_settings')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
